### ISSUE TITLE
Undefined method keys

### ISSUE THREAD

**Issue by jcoyne** [splitwise/super_diff#254]
This looks like #202, but that was supposed to have been fixed in 0.11.0.  I'm seeing this in 0.12.1:

```
     NoMethodError:
       undefined method `keys' for nil:NilClass
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:71:in `insert_hash_inspection_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/basic/inspection_tree_builders/custom_object.rb:23:in `block (2 levels) in call'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:55:in `evaluate_block'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:92:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/nesting.rb:14:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:95:in `block in inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:23:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:85:in `inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:20:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:21:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:16:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/as_lines_when_rendering_to_lines.rb:32:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/nesting.rb:14:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/only_when.rb:21:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:95:in `block in inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:23:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:85:in `inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:20:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:21:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:16:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/as_lines_when_rendering_to_lines.rb:32:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/nesting.rb:14:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/only_when.rb:21:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:95:in `block in inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:23:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:85:in `inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:20:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:21:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:16:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/as_lines_when_rendering_to_lines.rb:32:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/nesting.rb:14:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/only_when.rb:21:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:95:in `block in inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:23:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:85:in `inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:20:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:21:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/inspection.rb:16:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/as_lines_when_rendering_to_lines.rb:32:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/nesting.rb:14:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/base.rb:93:in `render_to_string_in_subtree'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree_nodes/only_when.rb:21:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:29:in `block in render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `each'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `reduce'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/inspection_tree.rb:28:in `render_to_string'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:95:in `block in inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/core/recursion_guard.rb:23:in `guarding_recursion_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff.rb:85:in `inspect_object'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/monkey_patches.rb:298:in `format'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_builders/base.rb:148:in `description_of'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_builders/be_predicate.rb:34:in `block in add_actual_value'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:121:in `evaluate'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:151:in `to_s'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:99:in `to_string_in_singleline_mode'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:59:in `map'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:59:in `to_string_in_singleline_mode'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:45:in `length_of_first_paragraph'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_template.rb:49:in `to_s'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/matcher_text_builders/base.rb:27:in `call'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/augmented_matcher.rb:29:in `build_failure_message'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/augmented_matcher.rb:12:in `failure_message'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/super_diff-0.12.1/lib/super_diff/rspec/monkey_patches.rb:25:in `handle_failure'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /<home>/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/requests/v1/publish_dro_spec.rb:159:in `block (3 levels) in <top (required)>

```

**Comment by jas14** [comment]
Hi @jcoyne thanks for reporting – can you please provide:

* a repro spec (ideally as pared down as possible)
* ~the RSpec version you're running this on~ EDIT: I see 3.13.1 in the stack trace, let me know if that's incorrect

**Comment by jcoyne** [comment]
@jas14 sorry, that was 3 months ago and I no longer recall the context I was working in.

**Comment by jas14** [comment]
@jcoyne no problem and apologies for the delay, the project was in a transition period at the time. If you encounter this again, please do let me know here.
