### ISSUE TITLE
Incompatibility with rspec-wait -- `uninitialized constant RSpec::Expectations::ExpectationTarget`

### ISSUE THREAD

**Issue by Nakilon** [splitwise/super_diff#272]
```console
$ tree -a
.
├── Gemfile
├── Gemfile.lock
├── .ruby-version
└── spec
    └── _spec.rb

$ cat .ruby-version 
2.7.8

$ cat  spec/_spec.rb 
require "super_diff/rspec"
require "rspec/wait"

$ cat Gemfile
source "https://rubygems.org"
gem "rspec-wait"
gem "super_diff"

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    attr_extras (7.1.0)
    diff-lcs (1.5.1)
    optimist (3.1.0)
    patience_diff (1.2.0)
      optimist (~> 3.0)
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.2)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.1)
    rspec-wait (0.0.10)
      rspec (>= 3.0)
    super_diff (0.9.0)
      attr_extras (>= 6.2.4)
      diff-lcs
      patience_diff

PLATFORMS
  ruby

DEPENDENCIES
  rspec-wait
  super_diff

BUNDLED WITH
   2.1.4
```
```console
$ bundle exec rspec

An error occurred while loading ./spec/_spec.rb.
Failure/Error: require "rspec/wait"

NameError:
  uninitialized constant RSpec::Expectations::ExpectationTarget
  Did you mean?  RSpec::Expectations::ExpectationHelper
# ./spec/_spec.rb:2:in `require'
# ./spec/_spec.rb:2:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.11679 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by jas14** [comment]
Hey @Nakilon , thanks for the detailed report. Looks like you're using Ruby 2.7, which is EOL.

The bad news is, we probably won't backport changes from v0.10.0 onward to v0.9.0, as we don't officially support EOL Ruby versions. The good news is, I can't reproduce this in `super_diff` v0.10.0 or the latest, v0.13.0.

If you can update to Ruby 3.0+ and the latest `super_diff` version, and are still running into this problem at that point, definitely let me know. (Note that 3.0 is also technically EOL, but we happen to support it for the time being.)
