### ISSUE TITLE
undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by mcmire** [splitwise/super_diff#57]
This happened when comparing two arrays of HashWithIndifferentAccess objects. I'm not actually sure what caused this. 

Backtrace:

```
super_diff-0.2.0/lib/super_diff/operations/unary_operation.rb:30:in `should_add_comma_after_displaying?'
super_diff-0.2.0/lib/super_diff/diff_formatters/collection.rb:73:in `handle_non_change_operation'
super_diff-0.2.0/lib/super_diff/diff_formatters/collection.rb:42:in `block in contents'
```

**Comment by mcmire** [comment]
Gonna close this as I haven't seen this in a while.
