### ISSUE TITLE
Version 0.4.0 does not load in Rails codebase

### ISSUE THREAD

**Issue by Mange** [splitwise/super_diff#68]
Trying to upgrade to 0.4.0 breaks our test suite as the gem fails to load because of ActiveRecord being referenced before it has been loaded.

```
[2020-01-22T05:21:33.596Z] Failure/Error: require "super_diff/rspec-rails"

[2020-01-22T05:21:33.596Z] 

[2020-01-22T05:21:33.596Z] NameError:

[2020-01-22T05:21:33.596Z]   uninitialized constant ActiveRecord

[2020-01-22T05:21:33.596Z]   Did you mean?  ActiveModel

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/active_record/monkey_patches.rb:2:in `<top (required)>'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/active_record.rb:39:in `require'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/active_record.rb:39:in `<top (required)>'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/rails.rb:1:in `require'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/rails.rb:1:in `<top (required)>'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/rspec-rails.rb:2:in `require'

[2020-01-22T05:21:33.596Z] # /usr/local/bundle/ruby/2.6.0/gems/super_diff-0.4.0/lib/super_diff/rspec-rails.rb:2:in `<top (required)>'

[2020-01-22T05:21:33.596Z] # ./spec/spec_helper.rb:11:in `require'

[2020-01-22T05:21:33.596Z] # ./spec/spec_helper.rb:11:in `<top (required)>'
```

Do we need to change some of the setup code? Is this related to #64 or #65 ? The previous version works flawlessly.

**Comment by mcmire** [comment]
I believe the reason why it worked before is because `active_record` was in the gemspec, and Bundler was probably autorequiring it when it autorequired `super_diff`. 

I get that this broke things for you, but I'm really wondering whether it's the responsibility of this gem to load ActiveRecord for you? It seems like either your project should be requiring ActiveRecord, or `active_record` should be in your Gemfile so that it gets autorequired, but either way that should happen _ahead_ of you requiring `super_diff` (because surely your project needs ActiveRecord to function?). What do you think about this?

**Comment by Mange** [comment]
> I believe the reason why it worked before is because `active_record` was in the gemspec, and Bundler was probably autorequiring it when it autorequired `super_diff`.

I had the same suspicion.

> I get that this broke things for you, […]

Just to be clear, I'm not considering this as something that "broke" my stuff. I could probably fix it, I merely wanted to report that this version bump was written in a way to make an upgrade requiring changes to our Rails app. I figured it *could* be a defect.

No ill will from me here at all! :smile: 

> […], but I'm really wondering whether it's the responsibility of this gem to load ActiveRecord for you? It seems like either your project should be requiring ActiveRecord, or `active_record` should be in your Gemfile […]

It's a basic Rails app with the recommended `require` line in my RSpec config. I assume `ActiveRecord` is loaded when needed during the Rails initialization.

> […] so that it gets autorequired, but either way that should happen _ahead_ of you requiring `super_diff` (because surely your project needs ActiveRecord to function?). What do you think about this?

I'm not sure that is how it's supposed to work, actually. However, understandings Rail's initialization logic requires years of study in my experience (I too have a gem with Rails integration over multiple versions of Rails).

However, the strange thing about this stack trace seems to be that `super_diff` assumes the `ActiveRecord` constant to be defined (as it's referencing it), but the changelog says that it's optional.

I originally guessed that this could mean that either you must still have `ActiveRecord` loaded in order to load `super_diff`, or `super_diff` tries to auto-discover the presence of `ActiveRecord` but checks something incorrectly. After all, why would it try to monkey patch `ActiveRecord` if that constant isn't loaded yet?

In either case, I might have some time to dig through the code tomorrow at work and answer these questions myself. Perhaps it's a combination of some other module in our codebase triggering a load of something else too early and getting some sort of conflict going.

We have one of those `spec_helper_light.rb`-style file that loads the bare minimum, not including Rails, so maybe there is some interaction there.
Can I trigger a load of the Rails-specific overrides at a later time when Rails is loaded and leave the non-Rails-specific `super_diff` stuff loaded at all times?

**Comment by Mange** [comment]
I checked it out now. I just had to move `require "super_diff/rspec-rails"` to below the line that requires the `environment.rb` file. :+1:

**Comment by mcmire** [comment]
Haha perfect. That would have been my next recommendation — glad you got it figured out!
