### ISSUE TITLE
Error when `aggregate_failures` is used

### ISSUE THREAD

**Issue by krisleech** [splitwise/super_diff#69]
```ruby
# $ ruby -W0 query.rb

require "bundler/inline"

gemfile(true, quiet: true) do
  source "https://rubygems.org"
  gem "rspec"
  gem "super_diff"
end

require "super_diff/rspec"

require 'rspec/autorun'

RSpec.describe 'test' do
  it 'causes an error', :aggregate_failures do
    expect([1,2,3]).to eq([:a, :b, 3])
    expect([1,2,3]).to eq([:a, :b, 4])
  end
end
```

```
rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:240:in `formatted_message_and_backtrace'
super_diff-0.4.0/lib/super_diff/rspec/monkey_patches.rb:104:in `colorized_message_lines'
super_diff-0.4.0/lib/super_diff/rspec/monkey_patches.rb:104:in `flat_map'
super_diff-0.4.0/lib/super_diff/rspec/monkey_patches.rb:104:in `each'
super_diff/rspec/monkey_patches.rb:105:in `block in colorized_message_lines': no implicit conversion of Symbol into Integer (TypeError)
```

* RSpec 3.9
* super_diff 0.4
* Ruby 2.6 and 2.7

**Comment by mcmire** [comment]
Hey, thanks for the report! I just released v0.4.1 today, which, while it doesn't test tests marked with `aggregate_failures` specifically, may address this issue. Do you mind giving it a shot?

**Comment by krisleech** [comment]
Great timing, the problem has gone away, thanks so much :heart:

**Comment by mcmire** [comment]
Haha perfect, glad to hear 😁
